services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - patient-service
      - notes-service
      - risk-service
    networks:
      - diabetes-network

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/patientdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=98741
    networks:
      - diabetes-network

  front-service:
    build:
      context: ./front-service
      dockerfile: Dockerfile
    container_name: front-service
    ports:
      - "8082:8082"
    depends_on:
      - gateway-service
    networks:
      - diabetes-network

  notes-service:
    build:
      context: ./notes-service
      dockerfile: Dockerfile
    container_name: notes-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/notesdb
    networks:
      - diabetes-network

  risk-service:
    build:
      context: ./risk-service
      dockerfile: Dockerfile
    container_name: risk-service
    ports:
      - "8084:8084"
    networks:
      - diabetes-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 98741
      MYSQL_DATABASE: patientdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - diabetes-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - diabetes-network

networks:
  diabetes-network:
    driver: bridge

volumes:
  mysql-data:
  mongodb-data: