spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081  # patient-service
          predicates:
            - Path=/patients/**